#!/bin/bash

#****************************************************************************************************#
#                                        REMCHAIN FULLNODE SETUP                                     #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# CONFIGURATION VARIABLES                                                                            #
#----------------------------------------------------------------------------------------------------#

create_data_dir="/root/data"
state_dir="/root/data/state"
blocks_dir="/root/data/blocks"
full_node_domain="remblock2.io"
create_config_dir="/root/config"
email_contact="contact@remblock.io"
remnode_log_file="/root/remnode.log"
config_file="/root/config/config.ini"
genesis_json_file="/root/genesis.json"
create_rocksdb_dir="/root/data/rocksdb"
create_shpdata_dir="/root/data/shpdata"
create_snapshot_dir="/root/data/snapshots"

#----------------------------------------------------------------------------------------------------#
# INSTALL APACHE WEB SERVER                                                                          #
#----------------------------------------------------------------------------------------------------#

sudo -S apt update && sudo -S apt upgrade -y
sudo apt install apache2 -y
sudo ufw allow 'Apache'
sudo mkdir /var/www/$full_node_domain
sudo chown -R $USER:$USER /var/www/$full_node_domain
sudo chmod -R 755 /var/www/$full_node_domain
echo -e "<html>\n<head>\n<title>Welcome to Your_domain!</title>\n</head>\n<body>\n<h1>Success! The $full_node_domain virtual host is working!</h1>\n</body>\n</html>" > ./var/www/$full_node_domain/index.html
echo -e "<VirtualHost *:80>\nServerAdmin $email_contact\nServerName $full_node_domain\nServerAlias www.$full_node_domain\nDocumentRoot /var/www/$full_node_domain\nErrorLog ${APACHE_LOG_DIR}/error.log\nCustomLog ${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>" > ./etc/apache2/sites-available/$full_node_domain.conf
sudo a2ensite $full_node_domain.conf
sudo a2dissite 000-default.conf
sudo systemctl restart apache2

#----------------------------------------------------------------------------------------------------#
# INSTALL AND INIT SSL CERTIFCATE                                                                    #
#----------------------------------------------------------------------------------------------------#

wget https://dl.eff.org/certbot-auto
sudo mv certbot-auto /usr/local/bin/certbot-auto
sudo chown root /usr/local/bin/certbot-auto
sudo chmod 0755 /usr/local/bin/certbot-auto
sudo /usr/local/bin/certbot-auto --apache --noninteractive --agree-tos --email $email_contact --domains $full_node_domain -y
echo "0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/certbot-auto renew" | sudo tee -a /etc/crontab > /dev/null

#----------------------------------------------------------------------------------------------------#
# CREATE DIRECTORY IF IT DOESN'T EXIST                                                               #
#----------------------------------------------------------------------------------------------------#

if [ ! -d "$create_data_dir" -o -d "$create_config_dir" -o -d "$create_rocksdb_dir" -o -d "$create_shpdata_dir" -o -d "$create_snapshot_dir" ]
then
  mkdir -p "$create_data_dir"
  mkdir -p "$create_config_dir"
  mkdir -p "$create_rocksdb_dir"
  mkdir -p "$create_shpdata_dir"
  mkdir -p "$create_snapshot_dir"
fi

#----------------------------------------------------------------------------------------------------#
# SETUP CONFIG DIRECTORY                                                                             #
#----------------------------------------------------------------------------------------------------#

echo -e "plugin = eosio::chain_api_plugin\n\nplugin = eosio::net_api_plugin\n\nhttp-server-address = 0.0.0.0:8888\n\np2p-listen-endpoint = 0.0.0.0:9876\n\n# https://remme.io\n\np2p-peer-address = p2p.remchain.remme.io:2087\n\nverbose-http-errors = true\n\nchain-state-db-size-mb = 100480\n\nreversible-blocks-db-size-mb = 10480" > ./config/config.ini

#----------------------------------------------------------------------------------------------------#
# INSTALL REMNODE PROTOCOL                                                                           #
#----------------------------------------------------------------------------------------------------#

wget https://github.com/Remmeauth/remprotocol/releases/download/0.4.1/remprotocol_0.4.1.amd64.deb 
sudo apt install ./remprotocol_0.4.1.amd64.deb

#----------------------------------------------------------------------------------------------------#
# FETCHING GENESIS JSON                                                                              #
#----------------------------------------------------------------------------------------------------#

wget https://remchain.remme.io/genesis.json

#----------------------------------------------------------------------------------------------------#
# RESTORE FROM SNAPSHOT                                                                              #
#----------------------------------------------------------------------------------------------------#

sudo wget https://github.com/remblock/REMChain-Remote-Snapshots/raw/master/setup-remote-snapshot 
sudo chmod u+x setup-remote-snapshot 
sudo ./setup-remote-snapshot
cd data
cd snapshots
sudo ./restore-remote-snapshot

#----------------------------------------------------------------------------------------------------#
# READJUST CONFIG DIRECTORY                                                                          #
#----------------------------------------------------------------------------------------------------#

cd ~
wget https://github.com/remblock/REMChain-Full-Node-Setup/raw/master/config.ini
cat /root/config.ini > /root/config/config.ini
rm /root/config.ini
echo "" >> /root/config/config.ini
wget https://raw.githubusercontent.com/remblock/REMChain-Peer-Lists/master/peer-lists/mainnet.ini
cat /root/mainnet.ini >> /root/config/config.ini
rm /root/mainnet.ini

#----------------------------------------------------------------------------------------------------#
# GRACEFULLY STOP REMNODE                                                                            #
#----------------------------------------------------------------------------------------------------#

remnode_pid=$(pgrep remnode)

if [ ! -z "$remnode_pid" ]; 
then
  if ps -p $remnode_pid > /dev/null; 
  then
    kill -SIGINT $remnode_pid
  fi
  while ps -p $remnode_pid > /dev/null; do
    sleep 1
  done
fi

#----------------------------------------------------------------------------------------------------#
# START REMNODE IN THE BACKGROUND                                                                    #
#----------------------------------------------------------------------------------------------------#

remnode --config-dir $create_config_dir --data-dir $create_data_dir --state-history-dir $create_shpdata_dir --disable-replay-opts >> $remnode_log_file 2>&1 &
sleep 4

while [ : ]
do

systemdt=$(date '+%Y-%m-%dT%H:%M')

if [ "$dt1" == "$systemdt" ] 
then
  break
else
  dt1=$(remcli get info | grep head_block_time | cut -c 23-38)
  dt1date=$(echo $dt1 | awk -F'T' '{print $1}' | awk -F'-' 'BEGIN {OFS="-"}{ print $3, $2, $1}')
  dt1time=$(echo $dt1 | awk -F'T' '{print $2}' | awk -F':' 'BEGIN {OFS=":"}{ print $1, $2}')
  dt2=$(tail -n 1 $remnode_log_file | awk '{print $2}'| awk -F'.' '{print $1}')
  dt2date=$(echo $dt2 | awk -F'T' '{print $1}' | awk -F'-' 'BEGIN {OFS="-"}{ print $3, $2, $1}')
  dt2time=$(echo $dt2 | awk -F'T' '{print $2}' | awk -F':' 'BEGIN {OFS=":"}{ print $1, $2}')

  echo "Fetching blocks for [${dt1date} | ${dt1time}] | Current block date [${dt2date} | ${dt2time}]"
fi

echo ""
sleep 2

done

#----------------------------------------------------------------------------------------------------#
# INSTALL CLANG 8 AND OTHER NEEDED TOOLS                                                             #
#----------------------------------------------------------------------------------------------------#

apt update && apt install -y wget gnupg
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

cat <<EOT >>/etc/apt/sources.list
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main
EOT

sudo -S apt update && sudo -S apt upgrade -y \
    autoconf2.13        \
    build-essential     \
    bzip2               \
    cargo               \
    clang-8             \
    git                 \
    libgmp-dev          \
    libpq-dev           \
    lld-8               \
    lldb-8              \
    ninja-build         \
    nodejs              \
    npm                 \
    pkg-config          \
    postgresql-server-dev-all \
    python2.7-dev       \
    python3-dev         \
    rustc               \
    zlib1g-dev
    
update-alternatives --install /usr/bin/clang clang /usr/bin/clang-8 100
update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-8 100

#----------------------------------------------------------------------------------------------------#
# INSTALL BOOST 1.70                                                                                 #
#----------------------------------------------------------------------------------------------------#

cd ~
wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
tar xf boost_1_70_0.tar.gz
cd boost_1_70_0
./bootstrap.sh
./b2 toolset=clang -j10 install

#----------------------------------------------------------------------------------------------------#
# INSTALL CMAKE 3.14.5                                                                               #
#----------------------------------------------------------------------------------------------------#

cd ~
wget https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5.tar.gz
tar xf cmake-3.14.5.tar.gz
cd cmake-3.14.5
./bootstrap --parallel=10
make -j10
make -j10 install

#----------------------------------------------------------------------------------------------------#
# INSTALL EOSIO CDT 1.6.2                                                                            #
#----------------------------------------------------------------------------------------------------#

cd ~
wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.6.2/eosio.cdt_1.6.2-1-ubuntu-18.04_amd64.deb
apt install -y ./eosio.cdt_1.6.2-1-ubuntu-18.04_amd64.deb

#----------------------------------------------------------------------------------------------------#
# BUILD HISTORY TOOLS                                                                                #
#----------------------------------------------------------------------------------------------------#

cd ~
git clone --recursive https://github.com/EOSIO/history-tools.git
cd history-tools
mkdir build
cd build
cmake -GNinja -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8 ..
bash -c "cd ../src && npm install node-fetch"
ninja

#****************************************************************************************************#
#                                     STARTING FULL NODE PROCESSES                                   #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# SET ENVIRONMENT VARIABLES                                                                          #
#----------------------------------------------------------------------------------------------------#

nohup ~/history-tools/build/combo-rocksdb --rdb-database $create_rocksdb_dir &> /dev/null &

#----------------------------------------------------------------------------------------------------#
# RESTART ALL PROCESSES ON REBOOT                                                                    #
#----------------------------------------------------------------------------------------------------#

echo '#!/bin/bash

create_rem_dir="/root/data"
create_config_dir="/root/config"
create_shpdata_dir="/root/data/shpdata"
remnode_log_file="/root/remnode.log"

sudo resize2fs /dev/nvme1n1

remnode --config-dir $create_config_dir --data-dir $create_rem_dir --state-history-dir $create_shpdata_dir --disable-replay-opts >> $remnode_log_file 2>&1 &

exit 0' > /etc/rc.local
sudo chmod +x /etc/rc.local

#----------------------------------------------------------------------------------------------------#
# SETUP GRACEFUL SHUTDOWN                                                                            #
#----------------------------------------------------------------------------------------------------#

echo '#!/bin/sh
remnode_pid=$(pgrep remnode)
if [ ! -z "$remnode_pid" ]; then
if ps -p $remnode_pid > /dev/null; then
kill -SIGINT $remnode_pid
fi
while ps -p $remnode_pid > /dev/null; do
sleep 1
done
fi
' > /root/node_shutdown.sh
echo '[Unit]
Description=Gracefully shut down remnode to avoid database dirty flag
DefaultDependencies=no
After=poweroff.target shutdown.target reboot.target halt.target kexec.target
Requires=network-online.target network.target
[Service]
Type=oneshot
ExecStop=/root/node_shutdown.sh
RemainAfterExit=yes
KillMode=none
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/node_shutdown.service
sudo chmod +x /root/node_shutdown.sh
systemctl daemon-reload
systemctl enable node_shutdown
systemctl restart node_shutdown

#----------------------------------------------------------------------------------------------------#
# CLEANUP INSTALLATION FILES                                                                         #
#----------------------------------------------------------------------------------------------------#

rm boost_1_70_0.tar.gz
rm cmake-3.14.5.tar.gz
rm remprotocol_0.4.1.amd64.deb 
rm eosio.cdt_1.6.2-1-ubuntu-18.04_amd64.deb
echo ""
echo "====================================="
echo "REMCHAIN-FULLNODE-SETUP HAS COMPLETED"
echo "====================================="
echo ""
